filetype plugin indent on

" Enables syntax highlighting
syntax on

" Makes the backspace key behave like you'd expect, and go through EVERYTHING
set backspace=indent,eol,start

" hidden buffers
set hidden

" Do not create swap files
set noswapfile

" Set runtimepath and vim config file
let $RTP=split(&runtimepath, ',')[0]
let $RC="${HOME}/.vim/vimrc"

" Always try to show 10 lines above and below the cursor location
set scrolloff=10

" Show line numbers
set number

" Set the path variable
set path=.,**

" Searching ignores case unless an upper case letter is present in the query
set ignorecase smartcase

" Begin searching while typing, hightlighting matches
set incsearch hlsearch

" System clipboard
set clipboard=unnamed

" Indentation character
let g:indentLine_char = '⦙'

" Install nerdtree https://github.com/preservim/nerdtree
let NERDTreeShowHidden=1
let NERDTreeIgnore=['\.git$[[dir]]']
map <C-n> :NERDTreeToggle<CR>
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") && v:this_session == "" | NERDTree | endif
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

" Split window
nmap ss :split<Return><C-w>w
nmap sv :vsplit<Return><C-w>w

" Load all plugins now.
" Plugins need to be added to runtimepath before helptags can be generated.
packloadall
" Load all of the helptags now, after plugins have been loaded.
" All messages and errors will be ignored.
silent! helptags ALL
